USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DCM_ReceiveStatus](
	[ReceiveStatusID] [nvarchar](2) NOT NULL,
	[Description] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_DCM_ReceiveStatus] PRIMARY KEY CLUSTERED 
(
	[ReceiveStatusID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DCM_ReceiveStatus] ADD  CONSTRAINT [DF_DCM_ReceiveStatus_Description]  DEFAULT ('') FOR [Description]
GO
