USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IDM_WBS](
	[WBSID] [nvarchar](8) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[WBSLevel] [int] NOT NULL,
	[ResponsibleAgencyID] [int] NULL,
 CONSTRAINT [PK_IDM_WBS] PRIMARY KEY CLUSTERED 
(
	[WBSID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[IDM_WBS]  WITH CHECK ADD  CONSTRAINT [FK_WBS_ResponsibleAgencyID] FOREIGN KEY([ResponsibleAgencyID])
REFERENCES [dbo].[IDM_ResponsibleAgency] ([ResponsibleAgencyID])
GO
ALTER TABLE [dbo].[IDM_WBS] CHECK CONSTRAINT [FK_WBS_ResponsibleAgencyID]
GO
ALTER TABLE [dbo].[IDM_WBS] ADD  CONSTRAINT [DF_IDM_WBS_WBSLevel]  DEFAULT ((0)) FOR [WBSLevel]
GO
