USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VR_BPGSTIN](
	[BPID] [nvarchar](9) NOT NULL,
	[GSTIN] [int] NOT NULL,
	[Description] [nvarchar](50) NULL,
 CONSTRAINT [PK_VR_BPGSTIN] PRIMARY KEY CLUSTERED 
(
	[BPID] ASC,
	[GSTIN] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VR_BPGSTIN]  WITH CHECK ADD  CONSTRAINT [FK_VR_BPGSTIN_BPID] FOREIGN KEY([BPID])
REFERENCES [dbo].[VR_BusinessPartner] ([BPID])
GO
ALTER TABLE [dbo].[VR_BPGSTIN] CHECK CONSTRAINT [FK_VR_BPGSTIN_BPID]
GO
