USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATN_RawPunch](
	[RecordID] [int] IDENTITY(1,1) NOT NULL,
	[PunchDate] [datetime] NOT NULL,
	[CardNo] [nvarchar](8) NOT NULL,
	[Punch1Time] [decimal](6, 2) NOT NULL,
	[Punch2Time] [decimal](6, 2) NOT NULL,
	[FinYear] [nvarchar](4) NOT NULL,
	[Processed] [bit] NOT NULL,
	[FirstPunchMachine] [nvarchar](100) NULL,
	[SecondPunchMachine] [nvarchar](100) NULL,
 CONSTRAINT [PK_ATN_RawPunch] PRIMARY KEY CLUSTERED 
(
	[RecordID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ATN_RawPunch] ON [dbo].[ATN_RawPunch] 
(
	[CardNo] ASC,
	[PunchDate] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ATN_RawPunch_1] ON [dbo].[ATN_RawPunch] 
(
	[FinYear] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ATN_RawPunch]  WITH CHECK ADD  CONSTRAINT [FK_ATN_RawPunch_ATN_FinYear] FOREIGN KEY([FinYear])
REFERENCES [dbo].[ATN_FinYear] ([FinYear])
GO
ALTER TABLE [dbo].[ATN_RawPunch] CHECK CONSTRAINT [FK_ATN_RawPunch_ATN_FinYear]
GO
ALTER TABLE [dbo].[ATN_RawPunch] ADD  CONSTRAINT [DF_ATN_RawPunch_Processed]  DEFAULT ((0)) FOR [Processed]
GO
