USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SPMT_HSNSACCodes](
	[BillType] [int] NOT NULL,
	[HSNSACCode] [nvarchar](20) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[Dsca] [nvarchar](50) NULL,
	[TaxRate] [decimal](18, 6) NULL,
 CONSTRAINT [PK_SPMT_HSNSACCodes] PRIMARY KEY CLUSTERED 
(
	[BillType] ASC,
	[HSNSACCode] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SPMT_HSNSACCodes]  WITH CHECK ADD  CONSTRAINT [FK_SPMT_HSNSACCodes_BillType] FOREIGN KEY([BillType])
REFERENCES [dbo].[SPMT_BillTypes] ([BillType])
GO
ALTER TABLE [dbo].[SPMT_HSNSACCodes] CHECK CONSTRAINT [FK_SPMT_HSNSACCodes_BillType]
GO
