USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYS_FinanceCompany](
	[FinanceCompany] [nvarchar](10) NOT NULL,
	[CompanyName] [nvarchar](100) NULL,
	[LogisticCompany] [nvarchar](10) NULL,
 CONSTRAINT [PK_SYS_FinanceCompany] PRIMARY KEY CLUSTERED 
(
	[FinanceCompany] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
