USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TOS_AlertsToUsers](
	[ProjectID] [nvarchar](6) NOT NULL,
	[UserID] [nvarchar](8) NOT NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_TOS_AlertsToUsers] PRIMARY KEY CLUSTERED 
(
	[ProjectID] ASC,
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TOS_AlertsToUsers]  WITH CHECK ADD  CONSTRAINT [FK_TOS_AlertsToUsers_ProjectID] FOREIGN KEY([ProjectID])
REFERENCES [dbo].[TOS_Projects] ([ProjectID])
GO
ALTER TABLE [dbo].[TOS_AlertsToUsers] CHECK CONSTRAINT [FK_TOS_AlertsToUsers_ProjectID]
GO
ALTER TABLE [dbo].[TOS_AlertsToUsers]  WITH CHECK ADD  CONSTRAINT [FK_TOS_AlertsToUsers_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[aspnet_users] ([LoginID])
GO
ALTER TABLE [dbo].[TOS_AlertsToUsers] CHECK CONSTRAINT [FK_TOS_AlertsToUsers_UserID]
GO
ALTER TABLE [dbo].[TOS_AlertsToUsers] ADD  CONSTRAINT [DF_TOS_AlertsToUsers_Active]  DEFAULT ((1)) FOR [Active]
GO
