USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COST_CSDataWOnGLGroup](
	[ProjectGroupID] [int] NOT NULL,
	[FinYear] [int] NOT NULL,
	[Quarter] [int] NOT NULL,
	[Revision] [int] NOT NULL,
	[WorkOrderTypeID] [int] NOT NULL,
	[GLGroupID] [int] NOT NULL,
	[CrAmount] [decimal](14, 2) NOT NULL,
	[DrAmount] [decimal](14, 2) NOT NULL,
	[Amount] [decimal](14, 2) NOT NULL,
	[CrFC] [decimal](14, 2) NOT NULL,
	[DrFC] [decimal](14, 2) NOT NULL,
	[NetFC] [decimal](14, 2) NOT NULL,
	[FC] [nvarchar](10) NULL,
 CONSTRAINT [PK_COST_CSDataWOnGLGroup] PRIMARY KEY CLUSTERED 
(
	[ProjectGroupID] ASC,
	[FinYear] ASC,
	[Quarter] ASC,
	[Revision] ASC,
	[WorkOrderTypeID] ASC,
	[GLGroupID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup]  WITH CHECK ADD  CONSTRAINT [FK_COST_CSDataWOnGLGroup_CostSheet] FOREIGN KEY([ProjectGroupID], [FinYear], [Quarter], [Revision])
REFERENCES [dbo].[COST_CostSheet] ([ProjectGroupID], [FinYear], [Quarter], [Revision])
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] CHECK CONSTRAINT [FK_COST_CSDataWOnGLGroup_CostSheet]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup]  WITH CHECK ADD  CONSTRAINT [FK_COST_CSDataWOnGLGroup_FinYear] FOREIGN KEY([FinYear])
REFERENCES [dbo].[COST_FinYear] ([FinYear])
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] CHECK CONSTRAINT [FK_COST_CSDataWOnGLGroup_FinYear]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup]  WITH CHECK ADD  CONSTRAINT [FK_COST_CSDataWOnGLGroup_GLGroupID] FOREIGN KEY([GLGroupID])
REFERENCES [dbo].[COST_GLGroups] ([GLGroupID])
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] CHECK CONSTRAINT [FK_COST_CSDataWOnGLGroup_GLGroupID]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup]  WITH CHECK ADD  CONSTRAINT [FK_COST_CSDataWOnGLGroup_ProjectGroupID] FOREIGN KEY([ProjectGroupID])
REFERENCES [dbo].[COST_ProjectGroups] ([ProjectGroupID])
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] CHECK CONSTRAINT [FK_COST_CSDataWOnGLGroup_ProjectGroupID]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup]  WITH CHECK ADD  CONSTRAINT [FK_COST_CSDataWOnGLGroup_Quarter] FOREIGN KEY([Quarter])
REFERENCES [dbo].[COST_Quarters] ([Quarter])
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] CHECK CONSTRAINT [FK_COST_CSDataWOnGLGroup_Quarter]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup]  WITH CHECK ADD  CONSTRAINT [FK_COST_CSDataWOnGLGroup_WorkOrderTypeID] FOREIGN KEY([WorkOrderTypeID])
REFERENCES [dbo].[COST_WorkOrderTypes] ([WorkOrderTypeID])
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] CHECK CONSTRAINT [FK_COST_CSDataWOnGLGroup_WorkOrderTypeID]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] ADD  CONSTRAINT [DF_COST_CSDataWOnGLGroup_CrAmount]  DEFAULT ((0)) FOR [CrAmount]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] ADD  CONSTRAINT [DF_COST_CSDataWOnGLGroup_DrAmount]  DEFAULT ((0)) FOR [DrAmount]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] ADD  CONSTRAINT [DF_COST_CSDataWOnGLGroup_Amount]  DEFAULT ((0)) FOR [Amount]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] ADD  CONSTRAINT [DF_COST_CSDataWOnGLGroup_CrFC]  DEFAULT ((0)) FOR [CrFC]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] ADD  CONSTRAINT [DF_COST_CSDataWOnGLGroup_DrFC]  DEFAULT ((0)) FOR [DrFC]
GO
ALTER TABLE [dbo].[COST_CSDataWOnGLGroup] ADD  CONSTRAINT [DF_COST_CSDataWOnGLGroup_NetFC]  DEFAULT ((0)) FOR [NetFC]
GO
