USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TOS_UserTasks](
	[UserID] [nvarchar](8) NOT NULL,
	[TaskID] [int] NOT NULL,
	[TaskTypeID] [nvarchar](2) NULL,
	[EntryEnabled] [bit] NOT NULL,
 CONSTRAINT [PK_TOS_UserTasks] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[TaskID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TOS_UserTasks]  WITH CHECK ADD  CONSTRAINT [FK_TOSUsr_TaskTypeID] FOREIGN KEY([TaskTypeID])
REFERENCES [dbo].[TOS_TaskTypes] ([TaskTypeID])
GO
ALTER TABLE [dbo].[TOS_UserTasks] CHECK CONSTRAINT [FK_TOSUsr_TaskTypeID]
GO
ALTER TABLE [dbo].[TOS_UserTasks]  WITH CHECK ADD  CONSTRAINT [FK_TOSUsr_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[aspnet_users] ([LoginID])
GO
ALTER TABLE [dbo].[TOS_UserTasks] CHECK CONSTRAINT [FK_TOSUsr_UserID]
GO
ALTER TABLE [dbo].[TOS_UserTasks] ADD  CONSTRAINT [DF_TOS_UserTasks_EntryEnabled]  DEFAULT ((0)) FOR [EntryEnabled]
GO
