USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WF_DBIcons](
	[DBIconID] [int] IDENTITY(1,1) NOT NULL,
	[IconName] [nvarchar](100) NULL,
	[IconStyle] [nvarchar](250) NULL,
 CONSTRAINT [PK_WF_DBIcons] PRIMARY KEY CLUSTERED 
(
	[DBIconID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
