USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[hrm_emp_bak](
	[CardNo] [nvarchar](8) NOT NULL,
	[Salute] [nvarchar](50) NOT NULL,
	[EmployeeName] [nvarchar](50) NOT NULL,
	[AliasName] [nvarchar](50) NOT NULL,
	[Gender] [nvarchar](1) NOT NULL,
	[C_DateOfJoining] [datetime] NULL,
	[C_CompanyID] [nvarchar](6) NULL,
	[C_DivisionID] [nvarchar](6) NULL,
	[C_OfficeID] [int] NULL,
	[C_DepartmentID] [nvarchar](6) NULL,
	[C_ProjectSiteID] [nvarchar](6) NULL,
	[C_DesignationID] [int] NULL,
	[C_BasicSalary] [decimal](12, 2) NULL,
	[C_StatusID] [nvarchar](2) NULL,
	[C_StatusRemark] [nvarchar](250) NULL,
	[C_JoinngStateID] [nvarchar](2) NULL,
	[C_RatingID] [nvarchar](3) NULL,
	[ActiveState] [bit] NULL,
	[ActiveStateEventName] [nvarchar](20) NULL,
	[U_UnderIncrement] [bit] NOT NULL,
	[U_NewBasicSalary] [decimal](12, 2) NULL,
	[C_IncrementOn] [datetime] NULL,
	[C_IncrementRemark] [nvarchar](250) NULL,
	[U_UnderPromotion] [bit] NOT NULL,
	[U_NewDesignationID] [int] NULL,
	[C_PromotionOn] [datetime] NULL,
	[C_PromotionRemark] [nvarchar](250) NULL,
	[U_UnderTransfer] [bit] NOT NULL,
	[U_CompanyID] [nvarchar](6) NULL,
	[U_DivisionID] [nvarchar](6) NULL,
	[U_OfficeID] [int] NULL,
	[U_DepartmentID] [nvarchar](6) NULL,
	[U_ProjectSiteID] [nvarchar](6) NULL,
	[U_ActiveState] [bit] NOT NULL,
	[C_TransferedOn] [datetime] NULL,
	[C_TransferRemark] [nvarchar](250) NULL,
	[U_UnderRating] [bit] NOT NULL,
	[U_NewRatingID] [nvarchar](3) NULL,
	[C_RatingDoneOn] [datetime] NULL,
	[C_RatingPoints] [decimal](8, 2) NULL,
	[C_RatingRemark] [nvarchar](250) NULL,
	[Resigned] [bit] NOT NULL,
	[C_ResignedOn] [datetime] NULL,
	[C_DateOfReleaving] [datetime] NULL,
	[C_ResignedRemark] [nvarchar](250) NULL,
	[Confirmed] [bit] NOT NULL,
	[C_ConfirmedOn] [datetime] NULL,
	[C_ConfirmationRemark] [nvarchar](250) NULL,
	[J_CompanyID] [nvarchar](6) NULL,
	[J_DivisionID] [nvarchar](6) NULL,
	[J_OfficeID] [int] NULL,
	[J_DepartmentID] [nvarchar](6) NULL,
	[J_ProjectSiteID] [nvarchar](6) NULL,
	[J_DesignationID] [int] NULL,
	[J_BasicSalary] [decimal](12, 2) NULL,
	[J_StatusID] [nvarchar](2) NULL,
	[J_StatusRemark] [nvarchar](250) NULL,
	[WorkingAreaID] [int] NULL,
	[FunctionalStatusID1] [int] NULL,
	[FunctionalStatusID2] [int] NULL,
	[FunctionalStatusID3] [int] NULL,
	[FunctionalStatusID4] [int] NULL,
	[EducationDetails] [nvarchar](250) NULL,
	[IncrementCompany] [nvarchar](6) NULL,
	[CareerStartedOn] [datetime] NULL,
	[QualificationID1] [int] NULL,
	[QualificationYear1] [nvarchar](4) NULL,
	[QualificationID2] [int] NULL,
	[QualificationYear2] [nvarchar](4) NULL,
	[DateOfBirth] [datetime] NULL,
	[BloodGroupID] [nvarchar](5) NULL,
	[FatherName] [nvarchar](50) NULL,
	[SpouseName] [nvarchar](50) NULL,
	[ContactNumbers] [nvarchar](100) NULL,
	[PermanentAddress] [nvarchar](250) NULL,
	[PermanentCity] [nvarchar](50) NULL,
	[CurrentAddress] [nvarchar](250) NULL,
	[CurrentCity] [nvarchar](50) NULL,
	[OfficeFileNumber] [nvarchar](50) NULL,
	[PFNumber] [nvarchar](50) NULL,
	[ESINumber] [nvarchar](50) NULL,
	[PAN] [nvarchar](20) NULL,
	[EMailID] [nvarchar](50) NULL,
	[Freezed] [bit] NOT NULL,
	[ModifiedBy] [nvarchar](20) NULL,
	[ModifiedOn] [datetime] NULL,
	[ModifiedEvent] [nvarchar](20) NULL,
	[VerificationRequired] [bit] NOT NULL,
	[VerifierID] [nvarchar](8) NULL,
	[ApprovalRequired] [bit] NOT NULL,
	[ApproverID] [nvarchar](8) NULL,
	[ResponsibleAgencyID] [int] NULL,
	[Contractual] [bit] NOT NULL,
	[VPNMailExpireOn] [datetime] NULL,
	[Blackberry] [bit] NULL,
	[CategoryID] [int] NULL,
	[NonTechnical] [bit] NULL,
	[TAVerifier] [nvarchar](8) NULL,
	[TAApprover] [nvarchar](8) NULL,
	[TASanctioningAuthority] [nvarchar](8) NULL,
	[TASelfApproval] [bit] NOT NULL,
	[SiteAllowanceApprover] [nvarchar](8) NULL
) ON [PRIMARY]
GO
