USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_CityTypes](
	[CityTypeID] [nvarchar](6) NOT NULL,
	[CityTypeName] [nvarchar](50) NULL,
 CONSTRAINT [PK_TA_CityTypes] PRIMARY KEY CLUSTERED 
(
	[CityTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
