USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAK_UnitSets](
	[UnitSetID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NULL,
	[BaseUnitID] [int] NULL,
 CONSTRAINT [PK_PAK_UnitSets] PRIMARY KEY CLUSTERED 
(
	[UnitSetID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAK_UnitSets]  WITH CHECK ADD  CONSTRAINT [FK_PAK_UnitSets_BaseUnitID] FOREIGN KEY([BaseUnitID])
REFERENCES [dbo].[PAK_Units] ([UnitID])
GO
ALTER TABLE [dbo].[PAK_UnitSets] CHECK CONSTRAINT [FK_PAK_UnitSets_BaseUnitID]
GO
