USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LDAP_EMailGroupUsers](
	[EMailGroupID] [int] NOT NULL,
	[CardNo] [nvarchar](8) NOT NULL,
	[UserName] [nvarchar](50) NULL,
 CONSTRAINT [PK_LDAP_EMailGroupUsers] PRIMARY KEY CLUSTERED 
(
	[EMailGroupID] ASC,
	[CardNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LDAP_EMailGroupUsers]  WITH CHECK ADD  CONSTRAINT [EMGU_CardNo] FOREIGN KEY([CardNo])
REFERENCES [dbo].[aspnet_users] ([LoginID])
GO
ALTER TABLE [dbo].[LDAP_EMailGroupUsers] CHECK CONSTRAINT [EMGU_CardNo]
GO
ALTER TABLE [dbo].[LDAP_EMailGroupUsers]  WITH CHECK ADD  CONSTRAINT [EMGU_EMailGroupID] FOREIGN KEY([EMailGroupID])
REFERENCES [dbo].[LDAP_EMailGroups] ([EMailGroupID])
GO
ALTER TABLE [dbo].[LDAP_EMailGroupUsers] CHECK CONSTRAINT [EMGU_EMailGroupID]
GO
