USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ELOG_BLDetails](
	[BLID] [nvarchar](9) NOT NULL,
	[SerialNo] [int] NOT NULL,
	[SizeAndTypeOfContainer] [nvarchar](50) NULL,
	[ContainerNumber] [nvarchar](50) NULL,
	[Remarks] [nvarchar](100) NULL,
 CONSTRAINT [PK_ELOG_BLDetails] PRIMARY KEY CLUSTERED 
(
	[BLID] ASC,
	[SerialNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELOG_BLDetails]  WITH CHECK ADD  CONSTRAINT [FK_ELOG_BLDetails_BLID] FOREIGN KEY([BLID])
REFERENCES [dbo].[ELOG_BLHeader] ([BLID])
GO
ALTER TABLE [dbo].[ELOG_BLDetails] CHECK CONSTRAINT [FK_ELOG_BLDetails_BLID]
GO
