USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADM_ITCallSubTypes](
	[CallTypeID] [nvarchar](20) NOT NULL,
	[CallSubTypeID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_ADM_ITCallSubTypes] PRIMARY KEY CLUSTERED 
(
	[CallTypeID] ASC,
	[CallSubTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADM_ITCallSubTypes]  WITH CHECK ADD  CONSTRAINT [FK_ADM_ITCallSubTypes_CallTypeID] FOREIGN KEY([CallTypeID])
REFERENCES [dbo].[ADM_ITCallTypes] ([CallTypeID])
GO
ALTER TABLE [dbo].[ADM_ITCallSubTypes] CHECK CONSTRAINT [FK_ADM_ITCallSubTypes_CallTypeID]
GO
