USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[punchdata](
	[entryid] [numeric](18, 0) NOT NULL,
	[cardno] [nchar](4) NOT NULL,
	[punchtime] [datetime] NOT NULL,
 CONSTRAINT [PK_punchdata_1] PRIMARY KEY CLUSTERED 
(
	[entryid] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
