USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SPMT_DBStatus](
	[DBStatusID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](30) NOT NULL,
	[BillStatusIDs] [nvarchar](100) NULL,
	[PAStatusIDs] [nvarchar](100) NULL,
 CONSTRAINT [PK_SPMT_DBStatus] PRIMARY KEY CLUSTERED 
(
	[DBStatusID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
