USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HRM_ServeyThemes](
	[ThemeID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[Details] [nvarchar](100) NULL,
	[ServeyID] [int] NULL,
 CONSTRAINT [PK_HRM_ServeyThemes] PRIMARY KEY CLUSTERED 
(
	[ThemeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HRM_ServeyThemes]  WITH CHECK ADD  CONSTRAINT [FK_HRM_ServeyThemes_HRM_Serveys] FOREIGN KEY([ServeyID])
REFERENCES [dbo].[HRM_Serveys] ([ServeyID])
GO
ALTER TABLE [dbo].[HRM_ServeyThemes] CHECK CONSTRAINT [FK_HRM_ServeyThemes_HRM_Serveys]
GO
