USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VPN_VLanVPNs](
	[VLanIP] [nvarchar](15) NOT NULL,
	[VPNIP] [nvarchar](15) NOT NULL,
	[Description] [nvarchar](50) NULL,
	[IPSeries] [nvarchar](15) NOT NULL,
	[Active] [bit] NOT NULL,
	[OnPublicDomain] [bit] NOT NULL,
 CONSTRAINT [PK_VPN_VLanVPNs] PRIMARY KEY CLUSTERED 
(
	[VLanIP] ASC,
	[VPNIP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VPN_VLanVPNs]  WITH CHECK ADD  CONSTRAINT [FK_VPN_VPNs_VLan] FOREIGN KEY([VLanIP])
REFERENCES [dbo].[VPN_VLans] ([VLanIP])
GO
ALTER TABLE [dbo].[VPN_VLanVPNs] CHECK CONSTRAINT [FK_VPN_VPNs_VLan]
GO
ALTER TABLE [dbo].[VPN_VLanVPNs] ADD  CONSTRAINT [DF_VPN_VLanVPNs_Active]  DEFAULT ((1)) FOR [Active]
GO
ALTER TABLE [dbo].[VPN_VLanVPNs] ADD  CONSTRAINT [DF_VPN_VLanVPNs_OnPublicDomain]  DEFAULT ((0)) FOR [OnPublicDomain]
GO
