USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HRM_Ratings](
	[RatingID] [nvarchar](3) NOT NULL,
	[Description] [nvarchar](30) NOT NULL,
	[sequence] [int] NOT NULL,
 CONSTRAINT [PK_HRM_Ratings] PRIMARY KEY CLUSTERED 
(
	[RatingID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HRM_Ratings] ADD  CONSTRAINT [DF_HRM_Ratings_Description]  DEFAULT ('') FOR [Description]
GO
ALTER TABLE [dbo].[HRM_Ratings] ADD  CONSTRAINT [DF_HRM_Ratings_sequence]  DEFAULT ((0)) FOR [sequence]
GO
