USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TOS_TaskRelation](
	[TaskID] [int] NOT NULL,
	[ChildID] [int] NOT NULL,
	[Sequence] [int] NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_TOS_TaskRelation] PRIMARY KEY CLUSTERED 
(
	[TaskID] ASC,
	[ChildID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TOS_TaskRelation] ADD  CONSTRAINT [DF_TOS_TaskRelation_Active]  DEFAULT ((0)) FOR [Active]
GO
