USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QCM_EmployeeGroupUsers](
	[GroupiD] [int] NOT NULL,
	[CardNo] [nvarchar](8) NOT NULL,
 CONSTRAINT [PK_QCM_EmployeeGroupUsers] PRIMARY KEY CLUSTERED 
(
	[GroupiD] ASC,
	[CardNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QCM_EmployeeGroupUsers]  WITH CHECK ADD  CONSTRAINT [FK_QCM_EGU_CardNo] FOREIGN KEY([CardNo])
REFERENCES [dbo].[HRM_Employees] ([CardNo])
GO
ALTER TABLE [dbo].[QCM_EmployeeGroupUsers] CHECK CONSTRAINT [FK_QCM_EGU_CardNo]
GO
ALTER TABLE [dbo].[QCM_EmployeeGroupUsers]  WITH CHECK ADD  CONSTRAINT [FK_QCM_EGU_GroupID] FOREIGN KEY([GroupiD])
REFERENCES [dbo].[QCM_EmployeeGroups] ([GroupID])
GO
ALTER TABLE [dbo].[QCM_EmployeeGroupUsers] CHECK CONSTRAINT [FK_QCM_EGU_GroupID]
GO
