USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADM_ITServices](
	[ITServiceID] [nvarchar](15) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[AlertAfterDays] [int] NOT NULL,
	[EMailGroup] [nvarchar](50) NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_ADM_ITServices] PRIMARY KEY CLUSTERED 
(
	[ITServiceID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ADM_ITServices] ON [dbo].[ADM_ITServices] 
(
	[Description] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADM_ITServices]  WITH CHECK ADD  CONSTRAINT [FK_ADM_ITServices_HRM_EMailGroups] FOREIGN KEY([EMailGroup])
REFERENCES [dbo].[HRM_EMailGroups] ([EMailGroup])
GO
ALTER TABLE [dbo].[ADM_ITServices] CHECK CONSTRAINT [FK_ADM_ITServices_HRM_EMailGroups]
GO
ALTER TABLE [dbo].[ADM_ITServices] ADD  CONSTRAINT [DF_ADM_ITServices_AlertAfterDays]  DEFAULT ((0)) FOR [AlertAfterDays]
GO
ALTER TABLE [dbo].[ADM_ITServices] ADD  CONSTRAINT [DF_ADM_ITServices_Active]  DEFAULT ((1)) FOR [Active]
GO
