USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_RegionTypes](
	[RegionTypeID] [nvarchar](10) NOT NULL,
	[RegionTypeName] [nvarchar](50) NULL,
 CONSTRAINT [PK_TA_RegionTypes] PRIMARY KEY CLUSTERED 
(
	[RegionTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
