USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TA_CalcMethod](
	[CalculationTypeID] [nvarchar](10) NOT NULL,
	[CalculationDescription] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_TA_CalcMethod] PRIMARY KEY CLUSTERED 
(
	[CalculationTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
