USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SPMT_IsgecGSTIN](
	[GSTID] [int] NOT NULL,
	[Description] [nvarchar](50) NULL,
	[State] [nchar](50) NULL,
	[CompanyName] [nvarchar](50) NULL,
	[Address1Line] [nvarchar](100) NULL,
	[Address2Line] [nvarchar](100) NULL,
	[PAN] [nvarchar](50) NULL,
	[CIN] [nvarchar](50) NULL,
 CONSTRAINT [PK_SPMT_IsgecGSTIN] PRIMARY KEY CLUSTERED 
(
	[GSTID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
