USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAK_UserPort](
	[UserID] [nvarchar](8) NOT NULL,
	[PortID] [int] NOT NULL,
	[Active] [bit] NOT NULL,
 CONSTRAINT [PK_PAK_UserPort] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC,
	[PortID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAK_UserPort]  WITH CHECK ADD  CONSTRAINT [FK_PAK_UserPort_PortID] FOREIGN KEY([PortID])
REFERENCES [dbo].[ELOG_Ports] ([PortID])
GO
ALTER TABLE [dbo].[PAK_UserPort] CHECK CONSTRAINT [FK_PAK_UserPort_PortID]
GO
ALTER TABLE [dbo].[PAK_UserPort]  WITH CHECK ADD  CONSTRAINT [FK_PAK_UserPort_UserID] FOREIGN KEY([UserID])
REFERENCES [dbo].[aspnet_users] ([LoginID])
GO
ALTER TABLE [dbo].[PAK_UserPort] CHECK CONSTRAINT [FK_PAK_UserPort_UserID]
GO
ALTER TABLE [dbo].[PAK_UserPort] ADD  CONSTRAINT [DF_PAK_UserPort_Active]  DEFAULT ((1)) FOR [Active]
GO
