USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VPN_IPs](
	[VPNIP] [nvarchar](15) NOT NULL,
	[UsedBy] [nvarchar](8) NULL,
	[Used] [bit] NULL,
 CONSTRAINT [PK_VPN_IPs] PRIMARY KEY CLUSTERED 
(
	[VPNIP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VPN_IPs]  WITH CHECK ADD  CONSTRAINT [FK_IPs_UsedBy] FOREIGN KEY([UsedBy])
REFERENCES [dbo].[aspnet_users] ([LoginID])
GO
ALTER TABLE [dbo].[VPN_IPs] CHECK CONSTRAINT [FK_IPs_UsedBy]
GO
ALTER TABLE [dbo].[VPN_IPs] ADD  CONSTRAINT [DF_VPN_IPs_Used]  DEFAULT ((0)) FOR [Used]
GO
