USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ELOG_ICDCFSs](
	[ICDCFSID] [int] IDENTITY(1,1) NOT NULL,
	[StuffingPointID] [int] NULL,
	[Description] [nvarchar](100) NULL,
 CONSTRAINT [PK_ELOG_ICDCFSs] PRIMARY KEY CLUSTERED 
(
	[ICDCFSID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELOG_ICDCFSs]  WITH CHECK ADD  CONSTRAINT [FK_ELOG_ICDCFSs_StuffingPointID] FOREIGN KEY([StuffingPointID])
REFERENCES [dbo].[ELOG_StuffingPoints] ([StuffingPointID])
GO
ALTER TABLE [dbo].[ELOG_ICDCFSs] CHECK CONSTRAINT [FK_ELOG_ICDCFSs_StuffingPointID]
GO
