USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ATH_DocumentSeries](
	[Series] [varchar](50) NOT NULL,
	[RunningNumber] [int] NOT NULL,
	[Active] [char](1) NOT NULL,
 CONSTRAINT [PK_ATH_DocumentSeries] PRIMARY KEY CLUSTERED 
(
	[RunningNumber] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
