USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spasmAstRAMSSelectByID]
  @RAMID NVarChar(10) 
  AS
  SELECT
		[ASM_AstRAMS].[RAMID],
		[ASM_AstRAMS].[Description] 
  FROM [ASM_AstRAMS] 
  WHERE
  [ASM_AstRAMS].[RAMID] = @RAMID
GO
