USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spPrkLedgerSelectByFinYear]
  @FinYear Int,
  @OrderBy NVarChar(50)
  AS
  SELECT
		[PRK_Ledger].[DocumentID],
		[PRK_Ledger].[EmployeeID],
		[PRK_Ledger].[PerkID],
		[PRK_Ledger].[TranType],
		[PRK_Ledger].[TranDate],
		[PRK_Ledger].[FinYear],
		[PRK_Ledger].[Value],
		[PRK_Ledger].[UOM],
		[PRK_Ledger].[Amount],
		[PRK_Ledger].[Remarks],
		[PRK_Ledger].[CreatedBy],
		[PRK_Employees1].[EmployeeID] AS PRK_Employees1_EmployeeID,
		[PRK_Employees1].[CardNo] AS PRK_Employees1_CardNo,
		[PRK_Employees1].[EmployeeName] AS PRK_Employees1_EmployeeName,
		[PRK_Employees1].[CategoryID] AS PRK_Employees1_CategoryID,
		[PRK_Employees1].[PostedAt] AS PRK_Employees1_PostedAt,
		[PRK_Employees1].[VehicleType] AS PRK_Employees1_VehicleType,
		[PRK_Employees1].[Basic] AS PRK_Employees1_Basic,
		[PRK_Employees1].[ESI] AS PRK_Employees1_ESI,
		[PRK_Employees1].[DOJ] AS PRK_Employees1_DOJ,
		[PRK_Employees1].[DOR] AS PRK_Employees1_DOR,
		[PRK_Employees1].[Department] AS PRK_Employees1_Department,
		[PRK_Employees1].[Company] AS PRK_Employees1_Company,
		[PRK_Perks2].[PerkID] AS PRK_Perks2_PerkID,
		[PRK_Perks2].[PerkCode] AS PRK_Perks2_PerkCode,
		[PRK_Perks2].[Description] AS PRK_Perks2_Description,
		[PRK_Perks2].[AdvanceApplicable] AS PRK_Perks2_AdvanceApplicable,
		[PRK_Perks2].[AdvanceMonths] AS PRK_Perks2_AdvanceMonths,
		[PRK_Perks2].[LockedMonths] AS PRK_Perks2_LockedMonths,
		[PRK_Perks2].[NoOfPayments] AS PRK_Perks2_NoOfPayments,
		[PRK_Perks2].[CarryForward] AS PRK_Perks2_CarryForward,
		[PRK_Perks2].[UOM] AS PRK_Perks2_UOM,
		[PRK_Perks2].[Active] AS PRK_Perks2_Active,
		[PRK_Perks2].[BaaNGL] AS PRK_Perks2_BaaNGL,
		[PRK_Perks2].[BaaNReference] AS PRK_Perks2_BaaNReference,
		[PRK_Perks2].[cmba] AS PRK_Perks2_cmba,
		[PRK_FinYears3].[FinYear] AS PRK_FinYears3_FinYear,
		[PRK_FinYears3].[Description] AS PRK_FinYears3_Description,
		[PRK_FinYears3].[StartDate] AS PRK_FinYears3_StartDate,
		[PRK_FinYears3].[EndDate] AS PRK_FinYears3_EndDate,
		[PRK_FinYears3].[Status] AS PRK_FinYears3_Status,
		[PRK_Employees4].[EmployeeID] AS PRK_Employees4_EmployeeID,
		[PRK_Employees4].[CardNo] AS PRK_Employees4_CardNo,
		[PRK_Employees4].[EmployeeName] AS PRK_Employees4_EmployeeName,
		[PRK_Employees4].[CategoryID] AS PRK_Employees4_CategoryID,
		[PRK_Employees4].[PostedAt] AS PRK_Employees4_PostedAt,
		[PRK_Employees4].[VehicleType] AS PRK_Employees4_VehicleType,
		[PRK_Employees4].[Basic] AS PRK_Employees4_Basic,
		[PRK_Employees4].[ESI] AS PRK_Employees4_ESI,
		[PRK_Employees4].[DOJ] AS PRK_Employees4_DOJ,
		[PRK_Employees4].[DOR] AS PRK_Employees4_DOR,
		[PRK_Employees4].[Department] AS PRK_Employees4_Department,
		[PRK_Employees4].[Company] AS PRK_Employees4_Company 
  FROM [PRK_Ledger] 
  INNER JOIN [PRK_Employees] AS [PRK_Employees1]
    ON [PRK_Ledger].[EmployeeID] = [PRK_Employees1].[EmployeeID]
  INNER JOIN [PRK_Perks] AS [PRK_Perks2]
    ON [PRK_Ledger].[PerkID] = [PRK_Perks2].[PerkID]
  INNER JOIN [PRK_FinYears] AS [PRK_FinYears3]
    ON [PRK_Ledger].[FinYear] = [PRK_FinYears3].[FinYear]
  INNER JOIN [PRK_Employees] AS [PRK_Employees4]
    ON [PRK_Ledger].[CreatedBy] = [PRK_Employees4].[EmployeeID]
  WHERE
  [PRK_Ledger].[FinYear] = @FinYear
  ORDER BY
     CASE @orderBy WHEN 'DocumentID' THEN [PRK_Ledger].[DocumentID] END,
     CASE @orderBy WHEN 'DocumentID DESC' THEN [PRK_Ledger].[DocumentID] END DESC,
     CASE @orderBy WHEN 'EmployeeID' THEN [PRK_Ledger].[EmployeeID] END,
     CASE @orderBy WHEN 'EmployeeID DESC' THEN [PRK_Ledger].[EmployeeID] END DESC,
     CASE @orderBy WHEN 'PerkID' THEN [PRK_Ledger].[PerkID] END,
     CASE @orderBy WHEN 'PerkID DESC' THEN [PRK_Ledger].[PerkID] END DESC,
     CASE @orderBy WHEN 'TranType' THEN [PRK_Ledger].[TranType] END,
     CASE @orderBy WHEN 'TranType DESC' THEN [PRK_Ledger].[TranType] END DESC,
     CASE @orderBy WHEN 'TranDate' THEN [PRK_Ledger].[TranDate] END,
     CASE @orderBy WHEN 'TranDate DESC' THEN [PRK_Ledger].[TranDate] END DESC,
     CASE @orderBy WHEN 'FinYear' THEN [PRK_Ledger].[FinYear] END,
     CASE @orderBy WHEN 'FinYear DESC' THEN [PRK_Ledger].[FinYear] END DESC,
     CASE @orderBy WHEN 'Value' THEN [PRK_Ledger].[Value] END,
     CASE @orderBy WHEN 'Value DESC' THEN [PRK_Ledger].[Value] END DESC,
     CASE @orderBy WHEN 'UOM' THEN [PRK_Ledger].[UOM] END,
     CASE @orderBy WHEN 'UOM DESC' THEN [PRK_Ledger].[UOM] END DESC,
     CASE @orderBy WHEN 'Amount' THEN [PRK_Ledger].[Amount] END,
     CASE @orderBy WHEN 'Amount DESC' THEN [PRK_Ledger].[Amount] END DESC,
     CASE @orderBy WHEN 'Remarks' THEN [PRK_Ledger].[Remarks] END,
     CASE @orderBy WHEN 'Remarks DESC' THEN [PRK_Ledger].[Remarks] END DESC,
     CASE @orderBy WHEN 'CreatedBy' THEN [PRK_Ledger].[CreatedBy] END,
     CASE @orderBy WHEN 'CreatedBy DESC' THEN [PRK_Ledger].[CreatedBy] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_EmployeeID' THEN [PRK_Employees1].[EmployeeID] END,
     CASE @orderBy WHEN 'PRK_Employees1_EmployeeID DESC' THEN [PRK_Employees1].[EmployeeID] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_CardNo' THEN [PRK_Employees1].[CardNo] END,
     CASE @orderBy WHEN 'PRK_Employees1_CardNo DESC' THEN [PRK_Employees1].[CardNo] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_EmployeeName' THEN [PRK_Employees1].[EmployeeName] END,
     CASE @orderBy WHEN 'PRK_Employees1_EmployeeName DESC' THEN [PRK_Employees1].[EmployeeName] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_CategoryID' THEN [PRK_Employees1].[CategoryID] END,
     CASE @orderBy WHEN 'PRK_Employees1_CategoryID DESC' THEN [PRK_Employees1].[CategoryID] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_PostedAt' THEN [PRK_Employees1].[PostedAt] END,
     CASE @orderBy WHEN 'PRK_Employees1_PostedAt DESC' THEN [PRK_Employees1].[PostedAt] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_VehicleType' THEN [PRK_Employees1].[VehicleType] END,
     CASE @orderBy WHEN 'PRK_Employees1_VehicleType DESC' THEN [PRK_Employees1].[VehicleType] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_Basic' THEN [PRK_Employees1].[Basic] END,
     CASE @orderBy WHEN 'PRK_Employees1_Basic DESC' THEN [PRK_Employees1].[Basic] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_ESI' THEN [PRK_Employees1].[ESI] END,
     CASE @orderBy WHEN 'PRK_Employees1_ESI DESC' THEN [PRK_Employees1].[ESI] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_DOJ' THEN [PRK_Employees1].[DOJ] END,
     CASE @orderBy WHEN 'PRK_Employees1_DOJ DESC' THEN [PRK_Employees1].[DOJ] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_DOR' THEN [PRK_Employees1].[DOR] END,
     CASE @orderBy WHEN 'PRK_Employees1_DOR DESC' THEN [PRK_Employees1].[DOR] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_Department' THEN [PRK_Employees1].[Department] END,
     CASE @orderBy WHEN 'PRK_Employees1_Department DESC' THEN [PRK_Employees1].[Department] END DESC,
     CASE @orderBy WHEN 'PRK_Employees1_Company' THEN [PRK_Employees1].[Company] END,
     CASE @orderBy WHEN 'PRK_Employees1_Company DESC' THEN [PRK_Employees1].[Company] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_PerkID' THEN [PRK_Perks2].[PerkID] END,
     CASE @orderBy WHEN 'PRK_Perks2_PerkID DESC' THEN [PRK_Perks2].[PerkID] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_PerkCode' THEN [PRK_Perks2].[PerkCode] END,
     CASE @orderBy WHEN 'PRK_Perks2_PerkCode DESC' THEN [PRK_Perks2].[PerkCode] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_Description' THEN [PRK_Perks2].[Description] END,
     CASE @orderBy WHEN 'PRK_Perks2_Description DESC' THEN [PRK_Perks2].[Description] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_AdvanceApplicable' THEN [PRK_Perks2].[AdvanceApplicable] END,
     CASE @orderBy WHEN 'PRK_Perks2_AdvanceApplicable DESC' THEN [PRK_Perks2].[AdvanceApplicable] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_AdvanceMonths' THEN [PRK_Perks2].[AdvanceMonths] END,
     CASE @orderBy WHEN 'PRK_Perks2_AdvanceMonths DESC' THEN [PRK_Perks2].[AdvanceMonths] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_LockedMonths' THEN [PRK_Perks2].[LockedMonths] END,
     CASE @orderBy WHEN 'PRK_Perks2_LockedMonths DESC' THEN [PRK_Perks2].[LockedMonths] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_NoOfPayments' THEN [PRK_Perks2].[NoOfPayments] END,
     CASE @orderBy WHEN 'PRK_Perks2_NoOfPayments DESC' THEN [PRK_Perks2].[NoOfPayments] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_CarryForward' THEN [PRK_Perks2].[CarryForward] END,
     CASE @orderBy WHEN 'PRK_Perks2_CarryForward DESC' THEN [PRK_Perks2].[CarryForward] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_UOM' THEN [PRK_Perks2].[UOM] END,
     CASE @orderBy WHEN 'PRK_Perks2_UOM DESC' THEN [PRK_Perks2].[UOM] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_Active' THEN [PRK_Perks2].[Active] END,
     CASE @orderBy WHEN 'PRK_Perks2_Active DESC' THEN [PRK_Perks2].[Active] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_BaaNGL' THEN [PRK_Perks2].[BaaNGL] END,
     CASE @orderBy WHEN 'PRK_Perks2_BaaNGL DESC' THEN [PRK_Perks2].[BaaNGL] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_BaaNReference' THEN [PRK_Perks2].[BaaNReference] END,
     CASE @orderBy WHEN 'PRK_Perks2_BaaNReference DESC' THEN [PRK_Perks2].[BaaNReference] END DESC,
     CASE @orderBy WHEN 'PRK_Perks2_cmba' THEN [PRK_Perks2].[cmba] END,
     CASE @orderBy WHEN 'PRK_Perks2_cmba DESC' THEN [PRK_Perks2].[cmba] END DESC,
     CASE @orderBy WHEN 'PRK_FinYears3_FinYear' THEN [PRK_FinYears3].[FinYear] END,
     CASE @orderBy WHEN 'PRK_FinYears3_FinYear DESC' THEN [PRK_FinYears3].[FinYear] END DESC,
     CASE @orderBy WHEN 'PRK_FinYears3_Description' THEN [PRK_FinYears3].[Description] END,
     CASE @orderBy WHEN 'PRK_FinYears3_Description DESC' THEN [PRK_FinYears3].[Description] END DESC,
     CASE @orderBy WHEN 'PRK_FinYears3_StartDate' THEN [PRK_FinYears3].[StartDate] END,
     CASE @orderBy WHEN 'PRK_FinYears3_StartDate DESC' THEN [PRK_FinYears3].[StartDate] END DESC,
     CASE @orderBy WHEN 'PRK_FinYears3_EndDate' THEN [PRK_FinYears3].[EndDate] END,
     CASE @orderBy WHEN 'PRK_FinYears3_EndDate DESC' THEN [PRK_FinYears3].[EndDate] END DESC,
     CASE @orderBy WHEN 'PRK_FinYears3_Status' THEN [PRK_FinYears3].[Status] END,
     CASE @orderBy WHEN 'PRK_FinYears3_Status DESC' THEN [PRK_FinYears3].[Status] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_EmployeeID' THEN [PRK_Employees4].[EmployeeID] END,
     CASE @orderBy WHEN 'PRK_Employees4_EmployeeID DESC' THEN [PRK_Employees4].[EmployeeID] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_CardNo' THEN [PRK_Employees4].[CardNo] END,
     CASE @orderBy WHEN 'PRK_Employees4_CardNo DESC' THEN [PRK_Employees4].[CardNo] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_EmployeeName' THEN [PRK_Employees4].[EmployeeName] END,
     CASE @orderBy WHEN 'PRK_Employees4_EmployeeName DESC' THEN [PRK_Employees4].[EmployeeName] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_CategoryID' THEN [PRK_Employees4].[CategoryID] END,
     CASE @orderBy WHEN 'PRK_Employees4_CategoryID DESC' THEN [PRK_Employees4].[CategoryID] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_PostedAt' THEN [PRK_Employees4].[PostedAt] END,
     CASE @orderBy WHEN 'PRK_Employees4_PostedAt DESC' THEN [PRK_Employees4].[PostedAt] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_VehicleType' THEN [PRK_Employees4].[VehicleType] END,
     CASE @orderBy WHEN 'PRK_Employees4_VehicleType DESC' THEN [PRK_Employees4].[VehicleType] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_Basic' THEN [PRK_Employees4].[Basic] END,
     CASE @orderBy WHEN 'PRK_Employees4_Basic DESC' THEN [PRK_Employees4].[Basic] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_ESI' THEN [PRK_Employees4].[ESI] END,
     CASE @orderBy WHEN 'PRK_Employees4_ESI DESC' THEN [PRK_Employees4].[ESI] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_DOJ' THEN [PRK_Employees4].[DOJ] END,
     CASE @orderBy WHEN 'PRK_Employees4_DOJ DESC' THEN [PRK_Employees4].[DOJ] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_DOR' THEN [PRK_Employees4].[DOR] END,
     CASE @orderBy WHEN 'PRK_Employees4_DOR DESC' THEN [PRK_Employees4].[DOR] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_Department' THEN [PRK_Employees4].[Department] END,
     CASE @orderBy WHEN 'PRK_Employees4_Department DESC' THEN [PRK_Employees4].[Department] END DESC,
     CASE @orderBy WHEN 'PRK_Employees4_Company' THEN [PRK_Employees4].[Company] END,
     CASE @orderBy WHEN 'PRK_Employees4_Company DESC' THEN [PRK_Employees4].[Company] END DESC
GO
