USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADM_ITCallStatus](
	[CallStatusID] [nvarchar](20) NOT NULL,
	[Description] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_ADM_ITCallStatus] PRIMARY KEY CLUSTERED 
(
	[CallStatusID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
