USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PMS_Mappings](
	[KeyGroup] [nvarchar](10) NOT NULL,
	[KeyName] [nvarchar](50) NOT NULL,
	[KeyValue] [nvarchar](50) NULL,
 CONSTRAINT [PK_PMS_Mappings] PRIMARY KEY CLUSTERED 
(
	[KeyGroup] ASC,
	[KeyName] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
