USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WF_DBRowTypes](
	[RowTypeID] [int] NOT NULL,
	[Description] [nvarchar](50) NULL,
	[cssClass] [nvarchar](50) NULL,
 CONSTRAINT [PK_WF_DBRowTypes] PRIMARY KEY CLUSTERED 
(
	[RowTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
