USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAK_Units](
	[UnitID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NULL,
	[UnitSetID] [int] NULL,
	[ConversionFactor] [decimal](18, 8) NOT NULL,
 CONSTRAINT [PK_PAK_Units] PRIMARY KEY CLUSTERED 
(
	[UnitID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PAK_Units]  WITH CHECK ADD  CONSTRAINT [FK_PAK_Units_UnitSetID] FOREIGN KEY([UnitSetID])
REFERENCES [dbo].[PAK_UnitSets] ([UnitSetID])
GO
ALTER TABLE [dbo].[PAK_Units] CHECK CONSTRAINT [FK_PAK_Units_UnitSetID]
GO
ALTER TABLE [dbo].[PAK_Units] ADD  CONSTRAINT [DF_PAK_Units_ConversionFactor]  DEFAULT ((0)) FOR [ConversionFactor]
GO
