USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATN_TranType](
	[TranType] [nvarchar](3) NOT NULL,
	[Description] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_ATN_TranType] PRIMARY KEY CLUSTERED 
(
	[TranType] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
