USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[QCM_RequestFiles](
	[RequestID] [int] NOT NULL,
	[SerialNo] [int] IDENTITY(1,1) NOT NULL,
	[FileName] [nvarchar](250) NOT NULL,
	[DiskFIleName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_QCM_RequestFiles] PRIMARY KEY CLUSTERED 
(
	[RequestID] ASC,
	[SerialNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[QCM_RequestFiles]  WITH CHECK ADD  CONSTRAINT [FK_QCM_RFiles_RequestID] FOREIGN KEY([RequestID])
REFERENCES [dbo].[QCM_Requests] ([RequestID])
GO
ALTER TABLE [dbo].[QCM_RequestFiles] CHECK CONSTRAINT [FK_QCM_RFiles_RequestID]
GO
