USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COST_GLNatures](
	[GLNatureID] [int] IDENTITY(1,1) NOT NULL,
	[GLNatureDescription] [nvarchar](50) NULL,
 CONSTRAINT [PK_COST_GLNatures] PRIMARY KEY CLUSTERED 
(
	[GLNatureID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
