USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[spatnApplHeaderSelectByCardNo]
  @FinYear NVarChar(4),
  @CardNo NVarChar(8),
  @OrderBy NVarChar(50),
  @RecordCount Int = 0 OUTPUT
  AS
  SELECT
		[ATN_ApplHeader].[LeaveApplID],
		[ATN_ApplHeader].[CardNo],
		[ATN_ApplHeader].[Remarks],
		[ATN_ApplHeader].[FinYear],
		[ATN_ApplHeader].[ApplStatusID],
		[ATN_ApplHeader].[AppliedOn],
		[ATN_ApplHeader].[VerificationOn],
		[ATN_ApplHeader].[ApprovalOn],
		[ATN_ApplHeader].[SanctionOn],
		[ATN_ApplHeader].[PostedOn],
		[ATN_ApplHeader].[VerificationRequired],
		[ATN_ApplHeader].[ApprovalRequired],
		[ATN_ApplHeader].[SanctionRequired],
		[ATN_ApplHeader].[VerifiedBy],
		[ATN_ApplHeader].[ApprovedBy],
		[ATN_ApplHeader].[SanctionedBy],
		[ATN_ApplHeader].[PostedBy],
		[ATN_ApplHeader].[VerificationRemark],
		[ATN_ApplHeader].[ApprovalRemark],
		[ATN_ApplHeader].[SanctionRemark],
		[HRM_Employees1].[CardNo] AS HRM_Employees1_CardNo,
		[HRM_Employees1].[EmployeeName] AS HRM_Employees1_EmployeeName,
		[HRM_Employees1].[VerificationRequired] AS HRM_Employees1_VerificationRequired,
		[HRM_Employees1].[VerifierID] AS HRM_Employees1_VerifierID,
		[HRM_Employees1].[ApprovalRequired] AS HRM_Employees1_ApprovalRequired,
		[HRM_Employees1].[ApproverID] AS HRM_Employees1_ApproverID,
		[HRM_Employees1].[C_DateOfJoining] AS HRM_Employees1_C_DateOfJoining,
		[HRM_Employees1].[C_DateOfReleaving] AS HRM_Employees1_C_DateOfReleaving,
		[HRM_Employees1].[C_CompanyID] AS HRM_Employees1_C_CompanyID,
		[HRM_Employees1].[C_DivisionID] AS HRM_Employees1_C_DivisionID,
		[HRM_Employees1].[C_OfficeID] AS HRM_Employees1_C_OfficeID,
		[HRM_Employees1].[C_DepartmentID] AS HRM_Employees1_C_DepartmentID,
		[HRM_Employees1].[C_DesignationID] AS HRM_Employees1_C_DesignationID,
		[HRM_Employees1].[ActiveState] AS HRM_Employees1_ActiveState,
		[ATN_ApplicationStatus2].[ApplStatusID] AS ATN_ApplicationStatus2_ApplStatusID,
		[ATN_ApplicationStatus2].[Description] AS ATN_ApplicationStatus2_Description,
		[HRM_Employees3].[CardNo] AS HRM_Employees3_CardNo,
		[HRM_Employees3].[EmployeeName] AS HRM_Employees3_EmployeeName,
		[HRM_Employees3].[VerificationRequired] AS HRM_Employees3_VerificationRequired,
		[HRM_Employees3].[VerifierID] AS HRM_Employees3_VerifierID,
		[HRM_Employees3].[ApprovalRequired] AS HRM_Employees3_ApprovalRequired,
		[HRM_Employees3].[ApproverID] AS HRM_Employees3_ApproverID,
		[HRM_Employees3].[C_DateOfJoining] AS HRM_Employees3_C_DateOfJoining,
		[HRM_Employees3].[C_DateOfReleaving] AS HRM_Employees3_C_DateOfReleaving,
		[HRM_Employees3].[C_CompanyID] AS HRM_Employees3_C_CompanyID,
		[HRM_Employees3].[C_DivisionID] AS HRM_Employees3_C_DivisionID,
		[HRM_Employees3].[C_OfficeID] AS HRM_Employees3_C_OfficeID,
		[HRM_Employees3].[C_DepartmentID] AS HRM_Employees3_C_DepartmentID,
		[HRM_Employees3].[C_DesignationID] AS HRM_Employees3_C_DesignationID,
		[HRM_Employees3].[ActiveState] AS HRM_Employees3_ActiveState,
		[HRM_Employees4].[CardNo] AS HRM_Employees4_CardNo,
		[HRM_Employees4].[EmployeeName] AS HRM_Employees4_EmployeeName,
		[HRM_Employees4].[VerificationRequired] AS HRM_Employees4_VerificationRequired,
		[HRM_Employees4].[VerifierID] AS HRM_Employees4_VerifierID,
		[HRM_Employees4].[ApprovalRequired] AS HRM_Employees4_ApprovalRequired,
		[HRM_Employees4].[ApproverID] AS HRM_Employees4_ApproverID,
		[HRM_Employees4].[C_DateOfJoining] AS HRM_Employees4_C_DateOfJoining,
		[HRM_Employees4].[C_DateOfReleaving] AS HRM_Employees4_C_DateOfReleaving,
		[HRM_Employees4].[C_CompanyID] AS HRM_Employees4_C_CompanyID,
		[HRM_Employees4].[C_DivisionID] AS HRM_Employees4_C_DivisionID,
		[HRM_Employees4].[C_OfficeID] AS HRM_Employees4_C_OfficeID,
		[HRM_Employees4].[C_DepartmentID] AS HRM_Employees4_C_DepartmentID,
		[HRM_Employees4].[C_DesignationID] AS HRM_Employees4_C_DesignationID,
		[HRM_Employees4].[ActiveState] AS HRM_Employees4_ActiveState,
		[HRM_Employees5].[CardNo] AS HRM_Employees5_CardNo,
		[HRM_Employees5].[EmployeeName] AS HRM_Employees5_EmployeeName,
		[HRM_Employees5].[VerificationRequired] AS HRM_Employees5_VerificationRequired,
		[HRM_Employees5].[VerifierID] AS HRM_Employees5_VerifierID,
		[HRM_Employees5].[ApprovalRequired] AS HRM_Employees5_ApprovalRequired,
		[HRM_Employees5].[ApproverID] AS HRM_Employees5_ApproverID,
		[HRM_Employees5].[C_DateOfJoining] AS HRM_Employees5_C_DateOfJoining,
		[HRM_Employees5].[C_DateOfReleaving] AS HRM_Employees5_C_DateOfReleaving,
		[HRM_Employees5].[C_CompanyID] AS HRM_Employees5_C_CompanyID,
		[HRM_Employees5].[C_DivisionID] AS HRM_Employees5_C_DivisionID,
		[HRM_Employees5].[C_OfficeID] AS HRM_Employees5_C_OfficeID,
		[HRM_Employees5].[C_DepartmentID] AS HRM_Employees5_C_DepartmentID,
		[HRM_Employees5].[C_DesignationID] AS HRM_Employees5_C_DesignationID,
		[HRM_Employees5].[ActiveState] AS HRM_Employees5_ActiveState,
		[HRM_Employees6].[CardNo] AS HRM_Employees6_CardNo,
		[HRM_Employees6].[EmployeeName] AS HRM_Employees6_EmployeeName,
		[HRM_Employees6].[VerificationRequired] AS HRM_Employees6_VerificationRequired,
		[HRM_Employees6].[VerifierID] AS HRM_Employees6_VerifierID,
		[HRM_Employees6].[ApprovalRequired] AS HRM_Employees6_ApprovalRequired,
		[HRM_Employees6].[ApproverID] AS HRM_Employees6_ApproverID,
		[HRM_Employees6].[C_DateOfJoining] AS HRM_Employees6_C_DateOfJoining,
		[HRM_Employees6].[C_DateOfReleaving] AS HRM_Employees6_C_DateOfReleaving,
		[HRM_Employees6].[C_CompanyID] AS HRM_Employees6_C_CompanyID,
		[HRM_Employees6].[C_DivisionID] AS HRM_Employees6_C_DivisionID,
		[HRM_Employees6].[C_OfficeID] AS HRM_Employees6_C_OfficeID,
		[HRM_Employees6].[C_DepartmentID] AS HRM_Employees6_C_DepartmentID,
		[HRM_Employees6].[C_DesignationID] AS HRM_Employees6_C_DesignationID,
		[HRM_Employees6].[ActiveState] AS HRM_Employees6_ActiveState 
  FROM [ATN_ApplHeader] 
  INNER JOIN [HRM_Employees] AS [HRM_Employees1]
    ON [ATN_ApplHeader].[CardNo] = [HRM_Employees1].[CardNo]
  INNER JOIN [ATN_ApplicationStatus] AS [ATN_ApplicationStatus2]
    ON [ATN_ApplHeader].[ApplStatusID] = [ATN_ApplicationStatus2].[ApplStatusID]
  LEFT OUTER JOIN [HRM_Employees] AS [HRM_Employees3]
    ON [ATN_ApplHeader].[VerifiedBy] = [HRM_Employees3].[CardNo]
  LEFT OUTER JOIN [HRM_Employees] AS [HRM_Employees4]
    ON [ATN_ApplHeader].[ApprovedBy] = [HRM_Employees4].[CardNo]
  LEFT OUTER JOIN [HRM_Employees] AS [HRM_Employees5]
    ON [ATN_ApplHeader].[SanctionedBy] = [HRM_Employees5].[CardNo]
  LEFT OUTER JOIN [HRM_Employees] AS [HRM_Employees6]
    ON [ATN_ApplHeader].[PostedBy] = [HRM_Employees6].[CardNo]
  WHERE
  [ATN_ApplHeader].[CardNo] = @CardNo
  AND [ATN_ApplHeader].[FinYear] = @FinYear
  ORDER BY
     CASE @orderBy WHEN 'LeaveApplID' THEN [ATN_ApplHeader].[LeaveApplID] END,
     CASE @orderBy WHEN 'LeaveApplID DESC' THEN [ATN_ApplHeader].[LeaveApplID] END DESC,
     CASE @orderBy WHEN 'CardNo' THEN [ATN_ApplHeader].[CardNo] END,
     CASE @orderBy WHEN 'CardNo DESC' THEN [ATN_ApplHeader].[CardNo] END DESC,
     CASE @orderBy WHEN 'Remarks' THEN [ATN_ApplHeader].[Remarks] END,
     CASE @orderBy WHEN 'Remarks DESC' THEN [ATN_ApplHeader].[Remarks] END DESC,
     CASE @orderBy WHEN 'FinYear' THEN [ATN_ApplHeader].[FinYear] END,
     CASE @orderBy WHEN 'FinYear DESC' THEN [ATN_ApplHeader].[FinYear] END DESC,
     CASE @orderBy WHEN 'ApplStatusID' THEN [ATN_ApplHeader].[ApplStatusID] END,
     CASE @orderBy WHEN 'ApplStatusID DESC' THEN [ATN_ApplHeader].[ApplStatusID] END DESC,
     CASE @orderBy WHEN 'AppliedOn' THEN [ATN_ApplHeader].[AppliedOn] END,
     CASE @orderBy WHEN 'AppliedOn DESC' THEN [ATN_ApplHeader].[AppliedOn] END DESC,
     CASE @orderBy WHEN 'VerificationOn' THEN [ATN_ApplHeader].[VerificationOn] END,
     CASE @orderBy WHEN 'VerificationOn DESC' THEN [ATN_ApplHeader].[VerificationOn] END DESC,
     CASE @orderBy WHEN 'ApprovalOn' THEN [ATN_ApplHeader].[ApprovalOn] END,
     CASE @orderBy WHEN 'ApprovalOn DESC' THEN [ATN_ApplHeader].[ApprovalOn] END DESC,
     CASE @orderBy WHEN 'SanctionOn' THEN [ATN_ApplHeader].[SanctionOn] END,
     CASE @orderBy WHEN 'SanctionOn DESC' THEN [ATN_ApplHeader].[SanctionOn] END DESC,
     CASE @orderBy WHEN 'PostedOn' THEN [ATN_ApplHeader].[PostedOn] END,
     CASE @orderBy WHEN 'PostedOn DESC' THEN [ATN_ApplHeader].[PostedOn] END DESC,
     CASE @orderBy WHEN 'VerificationRequired' THEN [ATN_ApplHeader].[VerificationRequired] END,
     CASE @orderBy WHEN 'VerificationRequired DESC' THEN [ATN_ApplHeader].[VerificationRequired] END DESC,
     CASE @orderBy WHEN 'ApprovalRequired' THEN [ATN_ApplHeader].[ApprovalRequired] END,
     CASE @orderBy WHEN 'ApprovalRequired DESC' THEN [ATN_ApplHeader].[ApprovalRequired] END DESC,
     CASE @orderBy WHEN 'SanctionRequired' THEN [ATN_ApplHeader].[SanctionRequired] END,
     CASE @orderBy WHEN 'SanctionRequired DESC' THEN [ATN_ApplHeader].[SanctionRequired] END DESC,
     CASE @orderBy WHEN 'VerifiedBy' THEN [ATN_ApplHeader].[VerifiedBy] END,
     CASE @orderBy WHEN 'VerifiedBy DESC' THEN [ATN_ApplHeader].[VerifiedBy] END DESC,
     CASE @orderBy WHEN 'ApprovedBy' THEN [ATN_ApplHeader].[ApprovedBy] END,
     CASE @orderBy WHEN 'ApprovedBy DESC' THEN [ATN_ApplHeader].[ApprovedBy] END DESC,
     CASE @orderBy WHEN 'SanctionedBy' THEN [ATN_ApplHeader].[SanctionedBy] END,
     CASE @orderBy WHEN 'SanctionedBy DESC' THEN [ATN_ApplHeader].[SanctionedBy] END DESC,
     CASE @orderBy WHEN 'PostedBy' THEN [ATN_ApplHeader].[PostedBy] END,
     CASE @orderBy WHEN 'PostedBy DESC' THEN [ATN_ApplHeader].[PostedBy] END DESC,
     CASE @orderBy WHEN 'VerificationRemark' THEN [ATN_ApplHeader].[VerificationRemark] END,
     CASE @orderBy WHEN 'VerificationRemark DESC' THEN [ATN_ApplHeader].[VerificationRemark] END DESC,
     CASE @orderBy WHEN 'ApprovalRemark' THEN [ATN_ApplHeader].[ApprovalRemark] END,
     CASE @orderBy WHEN 'ApprovalRemark DESC' THEN [ATN_ApplHeader].[ApprovalRemark] END DESC,
     CASE @orderBy WHEN 'SanctionRemark' THEN [ATN_ApplHeader].[SanctionRemark] END,
     CASE @orderBy WHEN 'SanctionRemark DESC' THEN [ATN_ApplHeader].[SanctionRemark] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_CardNo' THEN [HRM_Employees1].[CardNo] END,
     CASE @orderBy WHEN 'HRM_Employees1_CardNo DESC' THEN [HRM_Employees1].[CardNo] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_EmployeeName' THEN [HRM_Employees1].[EmployeeName] END,
     CASE @orderBy WHEN 'HRM_Employees1_EmployeeName DESC' THEN [HRM_Employees1].[EmployeeName] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_VerificationRequired' THEN [HRM_Employees1].[VerificationRequired] END,
     CASE @orderBy WHEN 'HRM_Employees1_VerificationRequired DESC' THEN [HRM_Employees1].[VerificationRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_VerifierID' THEN [HRM_Employees1].[VerifierID] END,
     CASE @orderBy WHEN 'HRM_Employees1_VerifierID DESC' THEN [HRM_Employees1].[VerifierID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_ApprovalRequired' THEN [HRM_Employees1].[ApprovalRequired] END,
     CASE @orderBy WHEN 'HRM_Employees1_ApprovalRequired DESC' THEN [HRM_Employees1].[ApprovalRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_ApproverID' THEN [HRM_Employees1].[ApproverID] END,
     CASE @orderBy WHEN 'HRM_Employees1_ApproverID DESC' THEN [HRM_Employees1].[ApproverID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_C_DateOfJoining' THEN [HRM_Employees1].[C_DateOfJoining] END,
     CASE @orderBy WHEN 'HRM_Employees1_C_DateOfJoining DESC' THEN [HRM_Employees1].[C_DateOfJoining] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_C_DateOfReleaving' THEN [HRM_Employees1].[C_DateOfReleaving] END,
     CASE @orderBy WHEN 'HRM_Employees1_C_DateOfReleaving DESC' THEN [HRM_Employees1].[C_DateOfReleaving] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_C_CompanyID' THEN [HRM_Employees1].[C_CompanyID] END,
     CASE @orderBy WHEN 'HRM_Employees1_C_CompanyID DESC' THEN [HRM_Employees1].[C_CompanyID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_C_DivisionID' THEN [HRM_Employees1].[C_DivisionID] END,
     CASE @orderBy WHEN 'HRM_Employees1_C_DivisionID DESC' THEN [HRM_Employees1].[C_DivisionID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_C_OfficeID' THEN [HRM_Employees1].[C_OfficeID] END,
     CASE @orderBy WHEN 'HRM_Employees1_C_OfficeID DESC' THEN [HRM_Employees1].[C_OfficeID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_C_DepartmentID' THEN [HRM_Employees1].[C_DepartmentID] END,
     CASE @orderBy WHEN 'HRM_Employees1_C_DepartmentID DESC' THEN [HRM_Employees1].[C_DepartmentID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_C_DesignationID' THEN [HRM_Employees1].[C_DesignationID] END,
     CASE @orderBy WHEN 'HRM_Employees1_C_DesignationID DESC' THEN [HRM_Employees1].[C_DesignationID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees1_ActiveState' THEN [HRM_Employees1].[ActiveState] END,
     CASE @orderBy WHEN 'HRM_Employees1_ActiveState DESC' THEN [HRM_Employees1].[ActiveState] END DESC,
     CASE @orderBy WHEN 'ATN_ApplicationStatus2_ApplStatusID' THEN [ATN_ApplicationStatus2].[ApplStatusID] END,
     CASE @orderBy WHEN 'ATN_ApplicationStatus2_ApplStatusID DESC' THEN [ATN_ApplicationStatus2].[ApplStatusID] END DESC,
     CASE @orderBy WHEN 'ATN_ApplicationStatus2_Description' THEN [ATN_ApplicationStatus2].[Description] END,
     CASE @orderBy WHEN 'ATN_ApplicationStatus2_Description DESC' THEN [ATN_ApplicationStatus2].[Description] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_CardNo' THEN [HRM_Employees3].[CardNo] END,
     CASE @orderBy WHEN 'HRM_Employees3_CardNo DESC' THEN [HRM_Employees3].[CardNo] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_EmployeeName' THEN [HRM_Employees3].[EmployeeName] END,
     CASE @orderBy WHEN 'HRM_Employees3_EmployeeName DESC' THEN [HRM_Employees3].[EmployeeName] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_VerificationRequired' THEN [HRM_Employees3].[VerificationRequired] END,
     CASE @orderBy WHEN 'HRM_Employees3_VerificationRequired DESC' THEN [HRM_Employees3].[VerificationRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_VerifierID' THEN [HRM_Employees3].[VerifierID] END,
     CASE @orderBy WHEN 'HRM_Employees3_VerifierID DESC' THEN [HRM_Employees3].[VerifierID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_ApprovalRequired' THEN [HRM_Employees3].[ApprovalRequired] END,
     CASE @orderBy WHEN 'HRM_Employees3_ApprovalRequired DESC' THEN [HRM_Employees3].[ApprovalRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_ApproverID' THEN [HRM_Employees3].[ApproverID] END,
     CASE @orderBy WHEN 'HRM_Employees3_ApproverID DESC' THEN [HRM_Employees3].[ApproverID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_C_DateOfJoining' THEN [HRM_Employees3].[C_DateOfJoining] END,
     CASE @orderBy WHEN 'HRM_Employees3_C_DateOfJoining DESC' THEN [HRM_Employees3].[C_DateOfJoining] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_C_DateOfReleaving' THEN [HRM_Employees3].[C_DateOfReleaving] END,
     CASE @orderBy WHEN 'HRM_Employees3_C_DateOfReleaving DESC' THEN [HRM_Employees3].[C_DateOfReleaving] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_C_CompanyID' THEN [HRM_Employees3].[C_CompanyID] END,
     CASE @orderBy WHEN 'HRM_Employees3_C_CompanyID DESC' THEN [HRM_Employees3].[C_CompanyID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_C_DivisionID' THEN [HRM_Employees3].[C_DivisionID] END,
     CASE @orderBy WHEN 'HRM_Employees3_C_DivisionID DESC' THEN [HRM_Employees3].[C_DivisionID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_C_OfficeID' THEN [HRM_Employees3].[C_OfficeID] END,
     CASE @orderBy WHEN 'HRM_Employees3_C_OfficeID DESC' THEN [HRM_Employees3].[C_OfficeID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_C_DepartmentID' THEN [HRM_Employees3].[C_DepartmentID] END,
     CASE @orderBy WHEN 'HRM_Employees3_C_DepartmentID DESC' THEN [HRM_Employees3].[C_DepartmentID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_C_DesignationID' THEN [HRM_Employees3].[C_DesignationID] END,
     CASE @orderBy WHEN 'HRM_Employees3_C_DesignationID DESC' THEN [HRM_Employees3].[C_DesignationID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees3_ActiveState' THEN [HRM_Employees3].[ActiveState] END,
     CASE @orderBy WHEN 'HRM_Employees3_ActiveState DESC' THEN [HRM_Employees3].[ActiveState] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_CardNo' THEN [HRM_Employees4].[CardNo] END,
     CASE @orderBy WHEN 'HRM_Employees4_CardNo DESC' THEN [HRM_Employees4].[CardNo] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_EmployeeName' THEN [HRM_Employees4].[EmployeeName] END,
     CASE @orderBy WHEN 'HRM_Employees4_EmployeeName DESC' THEN [HRM_Employees4].[EmployeeName] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_VerificationRequired' THEN [HRM_Employees4].[VerificationRequired] END,
     CASE @orderBy WHEN 'HRM_Employees4_VerificationRequired DESC' THEN [HRM_Employees4].[VerificationRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_VerifierID' THEN [HRM_Employees4].[VerifierID] END,
     CASE @orderBy WHEN 'HRM_Employees4_VerifierID DESC' THEN [HRM_Employees4].[VerifierID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_ApprovalRequired' THEN [HRM_Employees4].[ApprovalRequired] END,
     CASE @orderBy WHEN 'HRM_Employees4_ApprovalRequired DESC' THEN [HRM_Employees4].[ApprovalRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_ApproverID' THEN [HRM_Employees4].[ApproverID] END,
     CASE @orderBy WHEN 'HRM_Employees4_ApproverID DESC' THEN [HRM_Employees4].[ApproverID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_C_DateOfJoining' THEN [HRM_Employees4].[C_DateOfJoining] END,
     CASE @orderBy WHEN 'HRM_Employees4_C_DateOfJoining DESC' THEN [HRM_Employees4].[C_DateOfJoining] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_C_DateOfReleaving' THEN [HRM_Employees4].[C_DateOfReleaving] END,
     CASE @orderBy WHEN 'HRM_Employees4_C_DateOfReleaving DESC' THEN [HRM_Employees4].[C_DateOfReleaving] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_C_CompanyID' THEN [HRM_Employees4].[C_CompanyID] END,
     CASE @orderBy WHEN 'HRM_Employees4_C_CompanyID DESC' THEN [HRM_Employees4].[C_CompanyID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_C_DivisionID' THEN [HRM_Employees4].[C_DivisionID] END,
     CASE @orderBy WHEN 'HRM_Employees4_C_DivisionID DESC' THEN [HRM_Employees4].[C_DivisionID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_C_OfficeID' THEN [HRM_Employees4].[C_OfficeID] END,
     CASE @orderBy WHEN 'HRM_Employees4_C_OfficeID DESC' THEN [HRM_Employees4].[C_OfficeID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_C_DepartmentID' THEN [HRM_Employees4].[C_DepartmentID] END,
     CASE @orderBy WHEN 'HRM_Employees4_C_DepartmentID DESC' THEN [HRM_Employees4].[C_DepartmentID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_C_DesignationID' THEN [HRM_Employees4].[C_DesignationID] END,
     CASE @orderBy WHEN 'HRM_Employees4_C_DesignationID DESC' THEN [HRM_Employees4].[C_DesignationID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees4_ActiveState' THEN [HRM_Employees4].[ActiveState] END,
     CASE @orderBy WHEN 'HRM_Employees4_ActiveState DESC' THEN [HRM_Employees4].[ActiveState] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_CardNo' THEN [HRM_Employees5].[CardNo] END,
     CASE @orderBy WHEN 'HRM_Employees5_CardNo DESC' THEN [HRM_Employees5].[CardNo] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_EmployeeName' THEN [HRM_Employees5].[EmployeeName] END,
     CASE @orderBy WHEN 'HRM_Employees5_EmployeeName DESC' THEN [HRM_Employees5].[EmployeeName] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_VerificationRequired' THEN [HRM_Employees5].[VerificationRequired] END,
     CASE @orderBy WHEN 'HRM_Employees5_VerificationRequired DESC' THEN [HRM_Employees5].[VerificationRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_VerifierID' THEN [HRM_Employees5].[VerifierID] END,
     CASE @orderBy WHEN 'HRM_Employees5_VerifierID DESC' THEN [HRM_Employees5].[VerifierID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_ApprovalRequired' THEN [HRM_Employees5].[ApprovalRequired] END,
     CASE @orderBy WHEN 'HRM_Employees5_ApprovalRequired DESC' THEN [HRM_Employees5].[ApprovalRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_ApproverID' THEN [HRM_Employees5].[ApproverID] END,
     CASE @orderBy WHEN 'HRM_Employees5_ApproverID DESC' THEN [HRM_Employees5].[ApproverID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_C_DateOfJoining' THEN [HRM_Employees5].[C_DateOfJoining] END,
     CASE @orderBy WHEN 'HRM_Employees5_C_DateOfJoining DESC' THEN [HRM_Employees5].[C_DateOfJoining] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_C_DateOfReleaving' THEN [HRM_Employees5].[C_DateOfReleaving] END,
     CASE @orderBy WHEN 'HRM_Employees5_C_DateOfReleaving DESC' THEN [HRM_Employees5].[C_DateOfReleaving] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_C_CompanyID' THEN [HRM_Employees5].[C_CompanyID] END,
     CASE @orderBy WHEN 'HRM_Employees5_C_CompanyID DESC' THEN [HRM_Employees5].[C_CompanyID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_C_DivisionID' THEN [HRM_Employees5].[C_DivisionID] END,
     CASE @orderBy WHEN 'HRM_Employees5_C_DivisionID DESC' THEN [HRM_Employees5].[C_DivisionID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_C_OfficeID' THEN [HRM_Employees5].[C_OfficeID] END,
     CASE @orderBy WHEN 'HRM_Employees5_C_OfficeID DESC' THEN [HRM_Employees5].[C_OfficeID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_C_DepartmentID' THEN [HRM_Employees5].[C_DepartmentID] END,
     CASE @orderBy WHEN 'HRM_Employees5_C_DepartmentID DESC' THEN [HRM_Employees5].[C_DepartmentID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_C_DesignationID' THEN [HRM_Employees5].[C_DesignationID] END,
     CASE @orderBy WHEN 'HRM_Employees5_C_DesignationID DESC' THEN [HRM_Employees5].[C_DesignationID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees5_ActiveState' THEN [HRM_Employees5].[ActiveState] END,
     CASE @orderBy WHEN 'HRM_Employees5_ActiveState DESC' THEN [HRM_Employees5].[ActiveState] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_CardNo' THEN [HRM_Employees6].[CardNo] END,
     CASE @orderBy WHEN 'HRM_Employees6_CardNo DESC' THEN [HRM_Employees6].[CardNo] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_EmployeeName' THEN [HRM_Employees6].[EmployeeName] END,
     CASE @orderBy WHEN 'HRM_Employees6_EmployeeName DESC' THEN [HRM_Employees6].[EmployeeName] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_VerificationRequired' THEN [HRM_Employees6].[VerificationRequired] END,
     CASE @orderBy WHEN 'HRM_Employees6_VerificationRequired DESC' THEN [HRM_Employees6].[VerificationRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_VerifierID' THEN [HRM_Employees6].[VerifierID] END,
     CASE @orderBy WHEN 'HRM_Employees6_VerifierID DESC' THEN [HRM_Employees6].[VerifierID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_ApprovalRequired' THEN [HRM_Employees6].[ApprovalRequired] END,
     CASE @orderBy WHEN 'HRM_Employees6_ApprovalRequired DESC' THEN [HRM_Employees6].[ApprovalRequired] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_ApproverID' THEN [HRM_Employees6].[ApproverID] END,
     CASE @orderBy WHEN 'HRM_Employees6_ApproverID DESC' THEN [HRM_Employees6].[ApproverID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_C_DateOfJoining' THEN [HRM_Employees6].[C_DateOfJoining] END,
     CASE @orderBy WHEN 'HRM_Employees6_C_DateOfJoining DESC' THEN [HRM_Employees6].[C_DateOfJoining] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_C_DateOfReleaving' THEN [HRM_Employees6].[C_DateOfReleaving] END,
     CASE @orderBy WHEN 'HRM_Employees6_C_DateOfReleaving DESC' THEN [HRM_Employees6].[C_DateOfReleaving] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_C_CompanyID' THEN [HRM_Employees6].[C_CompanyID] END,
     CASE @orderBy WHEN 'HRM_Employees6_C_CompanyID DESC' THEN [HRM_Employees6].[C_CompanyID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_C_DivisionID' THEN [HRM_Employees6].[C_DivisionID] END,
     CASE @orderBy WHEN 'HRM_Employees6_C_DivisionID DESC' THEN [HRM_Employees6].[C_DivisionID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_C_OfficeID' THEN [HRM_Employees6].[C_OfficeID] END,
     CASE @orderBy WHEN 'HRM_Employees6_C_OfficeID DESC' THEN [HRM_Employees6].[C_OfficeID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_C_DepartmentID' THEN [HRM_Employees6].[C_DepartmentID] END,
     CASE @orderBy WHEN 'HRM_Employees6_C_DepartmentID DESC' THEN [HRM_Employees6].[C_DepartmentID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_C_DesignationID' THEN [HRM_Employees6].[C_DesignationID] END,
     CASE @orderBy WHEN 'HRM_Employees6_C_DesignationID DESC' THEN [HRM_Employees6].[C_DesignationID] END DESC,
     CASE @orderBy WHEN 'HRM_Employees6_ActiveState' THEN [HRM_Employees6].[ActiveState] END,
     CASE @orderBy WHEN 'HRM_Employees6_ActiveState DESC' THEN [HRM_Employees6].[ActiveState] END DESC 
  SET @RecordCount = @@RowCount
GO
