USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DCM_WebUsers](
	[UserID] [nvarchar](20) NOT NULL,
	[UserName] [nvarchar](40) NOT NULL,
	[CreatedBy] [nvarchar](8) NOT NULL,
	[ActivateOn] [datetime] NULL,
	[TillDays] [decimal](3, 0) NULL,
 CONSTRAINT [PK_DCM_WebUsers] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
