USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAL_Priority](
	[Priority] [nvarchar](1) NOT NULL,
	[Description] [nvarchar](30) NULL,
 CONSTRAINT [PK_CAL_Priority] PRIMARY KEY CLUSTERED 
(
	[Priority] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
