USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IDM_TransmittalTypes](
	[TmtlTypeID] [nvarchar](2) NOT NULL,
	[Description] [nvarchar](50) NULL,
 CONSTRAINT [PK_IDM_TransmittalTypes] PRIMARY KEY CLUSTERED 
(
	[TmtlTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
