USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATN_CardReplacement](
	[ReplacedCardNo] [nvarchar](8) NOT NULL,
	[CardNo] [nvarchar](8) NOT NULL,
 CONSTRAINT [PK_ATN_CardReplacement] PRIMARY KEY CLUSTERED 
(
	[ReplacedCardNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ATN_CardReplacement]  WITH CHECK ADD  CONSTRAINT [FK_ATN_CardReplacement_HRM_Employees] FOREIGN KEY([CardNo])
REFERENCES [dbo].[HRM_Employees] ([CardNo])
GO
ALTER TABLE [dbo].[ATN_CardReplacement] CHECK CONSTRAINT [FK_ATN_CardReplacement_HRM_Employees]
GO
