USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HRM_Offices](
	[OfficeID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[Address] [nvarchar](250) NOT NULL,
	[City] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_HRM_Offices] PRIMARY KEY CLUSTERED 
(
	[OfficeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HRM_Offices] ADD  CONSTRAINT [DF_HRM_Offices_Description]  DEFAULT ('') FOR [Description]
GO
ALTER TABLE [dbo].[HRM_Offices] ADD  CONSTRAINT [DF_HRM_Offices_Address]  DEFAULT ('') FOR [Address]
GO
ALTER TABLE [dbo].[HRM_Offices] ADD  CONSTRAINT [DF_HRM_Offices_City]  DEFAULT ('') FOR [City]
GO
