USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ELOG_DetentionBillTypes](
	[BillTypeID] [int] NOT NULL,
	[Description] [varchar](50) NULL,
 CONSTRAINT [PK_ELOG_DetentionBillTypes] PRIMARY KEY CLUSTERED 
(
	[BillTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
