USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WF_WorkFlows](
	[WFID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](100) NULL,
	[Active] [bit] NOT NULL,
	[ParentWFID] [int] NULL,
	[ChildWFID] [int] NULL,
 CONSTRAINT [PK_WF_WorkFlows] PRIMARY KEY CLUSTERED 
(
	[WFID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WF_WorkFlows] ADD  CONSTRAINT [DF_WF_WorkFlows_Active]  DEFAULT ((0)) FOR [Active]
GO
