USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ELOG_Carriers](
	[CarrierID] [int] IDENTITY(1,1) NOT NULL,
	[ShipmentModeID] [int] NULL,
	[Description] [nvarchar](100) NULL,
 CONSTRAINT [PK_ELOG_Carriers] PRIMARY KEY CLUSTERED 
(
	[CarrierID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ELOG_Carriers]  WITH CHECK ADD  CONSTRAINT [FK_ELOG_Carriers_ShipmentModeID] FOREIGN KEY([ShipmentModeID])
REFERENCES [dbo].[ELOG_ShipmentModes] ([ShipmentModeID])
GO
ALTER TABLE [dbo].[ELOG_Carriers] CHECK CONSTRAINT [FK_ELOG_Carriers_ShipmentModeID]
GO
