USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HRM_JoiningStates](
	[JoiningStateID] [nvarchar](2) NOT NULL,
	[Description] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_HRM_JoiningStates] PRIMARY KEY CLUSTERED 
(
	[JoiningStateID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
