USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sppakTCPOLRDDelete]
  @Original_SerialNo Int,
  @Original_ItemNo Int,
  @Original_UploadNo Int,
  @Original_DocSerialNo Int,
  @RowCount int = null OUTPUT
  AS
  DELETE [PAK_POLineRecDoc]
  WHERE
  [PAK_POLineRecDoc].[SerialNo] = @Original_SerialNo
  AND [PAK_POLineRecDoc].[ItemNo] = @Original_ItemNo
  AND [PAK_POLineRecDoc].[UploadNo] = @Original_UploadNo
  AND [PAK_POLineRecDoc].[DocSerialNo] = @Original_DocSerialNo
  AND [PAK_POLineRecDoc].[AutoGenerated] = 0 
  SET @RowCount = @@RowCount
GO
