USE [IJTPerks]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ATN_SABySI](
	[SerialNo] [int] IDENTITY(1,1) NOT NULL,
	[FinYear] [nvarchar](4) NULL,
	[MonthID] [int] NULL,
	[ProjectID] [nvarchar](6) NULL,
	[SiteName] [nvarchar](50) NULL,
	[Remarks] [nvarchar](250) NULL,
	[VerifiedBy] [nvarchar](8) NULL,
	[VerifiedOn] [datetime] NULL,
	[SAStatusID] [int] NULL,
	[FileName] [nvarchar](100) NULL,
	[DiskFileName] [nvarchar](250) NULL,
 CONSTRAINT [PK_ATN_SABySI] PRIMARY KEY CLUSTERED 
(
	[SerialNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ATN_SABySI]  WITH CHECK ADD  CONSTRAINT [FK_ATN_SABySI_FinYear] FOREIGN KEY([FinYear])
REFERENCES [dbo].[ATN_FinYear] ([FinYear])
GO
ALTER TABLE [dbo].[ATN_SABySI] CHECK CONSTRAINT [FK_ATN_SABySI_FinYear]
GO
ALTER TABLE [dbo].[ATN_SABySI]  WITH CHECK ADD  CONSTRAINT [FK_ATN_SABySI_MonthID] FOREIGN KEY([MonthID])
REFERENCES [dbo].[ATN_Months] ([MonthID])
GO
ALTER TABLE [dbo].[ATN_SABySI] CHECK CONSTRAINT [FK_ATN_SABySI_MonthID]
GO
ALTER TABLE [dbo].[ATN_SABySI]  WITH CHECK ADD  CONSTRAINT [FK_ATN_SABySI_ProjectID] FOREIGN KEY([ProjectID])
REFERENCES [dbo].[IDM_Projects] ([ProjectID])
GO
ALTER TABLE [dbo].[ATN_SABySI] CHECK CONSTRAINT [FK_ATN_SABySI_ProjectID]
GO
ALTER TABLE [dbo].[ATN_SABySI]  WITH CHECK ADD  CONSTRAINT [FK_ATN_SABySI_SAStatusID] FOREIGN KEY([SAStatusID])
REFERENCES [dbo].[ATN_ApplicationStatus] ([ApplStatusID])
GO
ALTER TABLE [dbo].[ATN_SABySI] CHECK CONSTRAINT [FK_ATN_SABySI_SAStatusID]
GO
ALTER TABLE [dbo].[ATN_SABySI]  WITH CHECK ADD  CONSTRAINT [FK_ATN_SABySI_VerifiedBy] FOREIGN KEY([VerifiedBy])
REFERENCES [dbo].[HRM_Employees] ([CardNo])
GO
ALTER TABLE [dbo].[ATN_SABySI] CHECK CONSTRAINT [FK_ATN_SABySI_VerifiedBy]
GO
