USE [master]
GO
CREATE DATABASE [IJTPerks] ON  PRIMARY 
( NAME = N'IJTPerks_bdd903ac12d84db7a2b57c722a5458f9_DAT', FILENAME = N'D:\PerksData\IJTPerks.MDF' , SIZE = 3861696KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5120KB )
 LOG ON 
( NAME = N'IJTPerks_TMP_log', FILENAME = N'D:\PerksData\IJTPerks_log.ldf' , SIZE = 199296KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO
ALTER DATABASE [IJTPerks] SET COMPATIBILITY_LEVEL = 90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IJTPerks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IJTPerks] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [IJTPerks] SET ANSI_NULLS OFF
GO
ALTER DATABASE [IJTPerks] SET ANSI_PADDING OFF
GO
ALTER DATABASE [IJTPerks] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [IJTPerks] SET ARITHABORT OFF
GO
ALTER DATABASE [IJTPerks] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [IJTPerks] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [IJTPerks] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [IJTPerks] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [IJTPerks] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [IJTPerks] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [IJTPerks] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [IJTPerks] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [IJTPerks] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [IJTPerks] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [IJTPerks] SET  DISABLE_BROKER
GO
ALTER DATABASE [IJTPerks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [IJTPerks] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [IJTPerks] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [IJTPerks] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [IJTPerks] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [IJTPerks] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [IJTPerks] SET  READ_WRITE
GO
ALTER DATABASE [IJTPerks] SET RECOVERY SIMPLE
GO
ALTER DATABASE [IJTPerks] SET  MULTI_USER
GO
ALTER DATABASE [IJTPerks] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [IJTPerks] SET DB_CHAINING OFF
GO
